# This is a basic workflow to help you deploy one bicep resource.
name: build storage account bicep


# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ none ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


env:
  AZURE_RESOURCEGROUP_NAME: demo-rg
  ENVIRONMENT_LOCATION: EastUS

jobs:
  # This workflow contains a single job called "build"
  bicep_build:
    name: bicep build 
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 0.0000005  

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
            creds: ${{ secrets.AZURE_SPN_CREDENTIAL }}

      - name: 'What-if'
        working-directory: '${{github.workspace}}/actions/bicep'
        run: |
          az deployment group create --what-if --resource-group demo-rg --template-file './storage.bicep' --parameters @parameters.json
  dev_deployment:
    name: dev deployment 
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: [bicep_build]
    environment: dev

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
            creds: ${{ secrets.AZURE_SPN_CREDENTIAL }}

      - name: 'deploy storage account bicep'
        working-directory: '${{github.workspace}}/actions/bicep'
        run: |
          az deployment group create --resource-group demo-rg --template-file './storage.bicep' --parameters @parameters.json

  
